# === Appearance ===============================================================
hide_window_decorations yes
background_opacity 0.85

# === Tmux Emulation ===========================================================

# Skip multiplexer (tmux/zellij) init by shell
env SKIP_MUX_INIT=1

# Options
allow_remote_control yes
enabled_layouts splits

# ─── Prefix Mappings ──────────────────────────────────────────────────────────
# Replace all instances of 'map ctrl+t>' below with your desired prefix key

# === Pane Splitting ===
map ctrl+t>% launch --cwd=current --location=vsplit
map ctrl+t>" launch --cwd=current --location=hsplit
#" <- to fix syntax highlighting

# === Pane Navigation ===
map ctrl+t>left neighboring_window left
map ctrl+t>right neighboring_window right
map ctrl+t>up neighboring_window up
map ctrl+t>down neighboring_window down
map ctrl+t>h neighboring_window left
map ctrl+t>l neighboring_window right
map ctrl+t>k neighboring_window up
map ctrl+t>j neighboring_window down

# === Pane Resizing ===
map ctrl+t>ctrl+h resize_window narrower
map ctrl+t>ctrl+l resize_window wider
map ctrl+t>ctrl+k resize_window taller
map ctrl+t>ctrl+j resize_window shorter
map ctrl+t>ctrl+* start_resizing_window

# === Pane Management ===
map ctrl+t>x close_window
map ctrl+t>z toggle_layout stack
map ctrl+t>m move_window_to_new_tab

# === Tab Management ===
map ctrl+t>c new_tab
map ctrl+t>n next_tab
map ctrl+t>p previous_tab
map ctrl+t>& close_tab
map ctrl+t>shift+l move_tab_forward
map ctrl+t>shirt+h move_tab_backward

# === Layouts ===
map ctrl+t>space kitten hints --program - --type=path

# === Scrollback and Copy ===
map ctrl+t>[ copy_to_clipboard
map ctrl+t>] paste_from_clipboard
map ctrl+t>page_up scroll_page_up
map ctrl+t>page_down scroll_page_down

# === Command Launcher ===
map ctrl+t>: kitty_shell

# === Config Reload ===
map ctrl+t>r load_config_file
